### ISSUE TITLE
MACos version on ICS is broken ?

### ISSUE THREAD

**Issue by davidvilanova** [imilne/tablet#2]
Hi,
Trying to download tablet from ICS website for MACOS i got package broken message.

<img width="672" alt="screenshot 2018-10-08 at 12 58 48" src="https://user-images.githubusercontent.com/11404840/46605564-384ceb80-cafa-11e8-83c1-4edd8c8fffb9.png">

**Comment by imilne** [comment]
What version of macOS?

**Comment by peterjc** [comment]
https://ics.hutton.ac.uk/resources/tablet/installers/tablet_macos_1_17_08_17.dmg seems fine for me on macOS Sierra 10.12.6 (which is now a little out of date).

**Comment by davidvilanova** [comment]
Running MacOs mojave 10.14

**Comment by imilne** [comment]
I can confirm the same thing on our Mojave macbook.

It's weird though: the file on the web server has an md5 checksum of be4901a36915c89482c0913c0ab25aac. If I copy it from the server via scp then it installs ok, but when downloaded (using Firefox), it claims to be corrupt, yet still has the correct checksum.

**Comment by davidvilanova** [comment]
Chrome has same problem:

I have used command line tools and it works.
`curl  https://ics.hutton.ac.uk/resources/tablet/installers/tablet_macos_1_17_08_17.dmg -o table.dmg`

**Comment by imilne** [comment]
I've rebuilt the installer - ensuring the latest version of our code signing certificate kicked in too - and it seems to work ok. The link is the same (checksum has changed obviously), but downloading via Firefox and then installing goes fine.

**Comment by davidvilanova** [comment]
Thanks for quick response @imilne  . Working with chrome as well now.
