### ISSUE TITLE
Need help understanding Tablet output of question marks (???)

### ISSUE THREAD

**Issue by tayabsoomro** [imilne/tablet#8]
I have a following entry in my SAM file:

```
PbPT3Sc00085    272     contig_1        162725  0       289M2D303M5I272M3D300M4D300M2D248M3D595M2D51M       *       0       0       *       *       NM:i:29 ms:i:4598       AS:i:4598       nn:i:0  tp:A:S  cm:i:407      s1:i:2255        de:f:0.0063     rl:i:0
```

As you can see instead of having a sequence in 10th column (SEQ), it has `*`. When I run this entire SAM file on Tablet, for the above alignment I get this output:

![image](https://user-images.githubusercontent.com/19979068/60272627-c3048f00-98b1-11e9-815f-68526e904191.png)

It shows a bunch of question marks for this alignment. I am not sure what that represents.

Also, is there a way to get the position with respect to the query sequence (in my case PbPT3Sc00085) where the alignment starts so that I can investigate the particular location of the query sequence?

**EDIT**
When I search up `PbPT3Sc00085` in all the contigs, it shows the length as `0` which makes sense since there is no alignment. The question I have is why does it show in the alignment pane if the length is `0`, is there a way to toggle it so that no read is shown if the length of its alignment is `0`?

![image](https://user-images.githubusercontent.com/19979068/60273248-eda31780-98b2-11e9-9d9d-982e04c9d4a9.png)

**Comment by peterjc** [comment]
How did you generate the SAM file?

Your read ``PbPT3Sc00085 `` does not contain the actual sequence (just a ``*`` entry), therefore tablet has no way to know what the bases were, so you get question marks.

The search results suggest that ``PbPT3Sc00085`` appears in the SAM file six times (you only showed the entry against ``contig_1`` here).

I have not checked the FLAG field, but my guess is that ``contig_14`` is the primary mapping (the entry with a length) while the rest are some kind of alternative mapping (which presumably explains where there is no length shown... although one could be computed from the CIGAR string in the ``contig_1`` case at least.

(As an aside, is it really a SAM file? Tablet will be much faster using an indexed BAM file; you should probably convert your SAM into BAM or generate the alignment that way to start with.)

**Comment by tayabsoomro** [comment]
The FLAG of 272 is (256+16), meaning that the read is reverse complemented and has a secondary alignment which is validated in the search results.

I used minimap2 to align two draft genomes together. I want to see the difference between them. 

On a completely separate note, the one draft genome (containing the PbPT3Sc...) was sequenced using 454 and therefore it contains lots of N's in it. I was wondering if there is a way to visualize the N's in the Tablet visualization.

And yes, I generated the indexed BAM file, I didn't mention it for brevity.

**Comment by peterjc** [comment]
Tablet does support SAM files directly, but has to index them itself - its a different path through the code to BAM using the BAI indexes, so that would have been worth stating. Also relevant, the version of tablet, and the OS you are using it under.

Tablet will show you Ns if you have them in your sequence (see also the import option to turn all DNA ambiguity codes into N).
